### ISSUE TITLE
As a router provider, I would like the ability to transfer liquidity between chains

### ISSUE THREAD

**Issue by alexwhte** [connext/monorepo#1268]
## Problem
 Routers today need to pull liquidity and use the bridge to move funds between chains. This is not an ideal user experience as they are the providers 

## Ideas to solve this
We could add a function to allow routers to do this directly

## Acceptance Criteria
[ ] Router can specify a source / destination chains and token 
[ ] Router can specify amount of liquidity to move 
[ ] Router can call a service to move their liquidity to the new chain
[ ] (tbd) Whatever fee structure makes sense here charges the router provider correclty
[ ] Feature is gated to router providers only in some way

## Other

**Comment by LayneHaber** [comment]
Are there other router liquidity convenience methods we should add? Specifically, I'm thinking we may want one that is able to `removeLiquidityAndSwap` so the `recipient` always receives the adopted asset on the chain they're receiving excess liquidity on.

cc @just-a-node @rhlsthrm

**Comment by LayneHaber** [comment]
> Should it just be an override for `removeLiquidity` that has a boolean for `receiveAdopted`? Seems less confusing that way.

Sure, could be. Are there any other, or just these two functionalities:

- [ ] remove + swap to adopted
- [ ] remove + move between chains + readd

**Comment by alexwhte** [comment]
Should be a wrapper contract

**Comment by jakekidd** [comment]
I was *about* to say "just pass in encoded `addRouterLiquidityFor` as the `execute` calldata" but then I remembered it's non-reentrant loll.

I'm not sure exactly how the separate contract solution would work (I see multicall *helping* but not solving the core problem). As far as I can tell, would require adding another call param or something so that `execute` can call `RoutersFacet._addLiquidityForRouter` (the internal method) directly to bypass the non-reentrancy for that specific case.

**Comment by LayneHaber** [comment]
not planned
