### ISSUE TITLE
[EXPLORER] Weird 'Load More' Behaviour

### ISSUE THREAD

**Issue by Tommy-R8** [connext/monorepo#2310]
**Describe the bug**
When looking at an address in the explorer, if there are no more transactions to show, the Load More button at the bottom behaves weirdly.

**To Reproduce**
1. Go to any address on Testnet Connextscan
2. Click on Load More until there are no more transactions to show
3. See error

**Expected behavior**
The site should display a message indicating that there are no more transactions to show, and it shouldn't bounce around like in the video.

**Screenshots**
https://discord.com/channels/454734546869551114/1037342032051568650/1037345580676026429

**Comment by pjenviri** [comment]
fixed.

**Comment by alexwhte** [comment]
@pjenviri This interaction still a bit weird. I think I expect this to load more transactions in my view, rather than more pages of transactions

Are we not loading all the pages because it slows down the UI? 
![image](https://user-images.githubusercontent.com/37959170/199797909-1e22957d-93fc-42fa-a7f7-b4eebc101470.png)
