### ISSUE TITLE
As a [end user], I want to see my balance on both chains (send/receive) in order to make it easier to chose an amount

### ISSUE THREAD

**Issue by 0xanedi** [connext/monorepo#2337]
## Problem
_Difficulty/extra work at deciding the amount to transfer; having to open a wallet to see amounts on receiver end_ 

## Proposed Solution
_We should show balance on both chains (send/receive) to solve this problem._
- [ ] See [Slingshot's ](https://app.slingshot.finance/) solution

## Acceptance Criteria
_From an end tester and/or user perspective, the below criteria must be met to consider this done:_
- [ ] Adding actual balance for sender/receiver chains

suggested by BM#8089

**Comment by alexwhte** [comment]
I think we can consider this better if with go forward flipping the horizontal chain alignment to the vertical swap/bridge alignment.  Looking at this

**Comment by alexwhte** [comment]
![image](https://user-images.githubusercontent.com/37959170/199854389-4c2c51f8-2a86-48f8-ba36-e9ea7f37a50e.png)

**Comment by 0xanedi** [comment]
Yeah I think that may be the way to go. Always liked Slingshot's approach despite it being just a DEX

**Comment by alexwhte** [comment]
Fair feedback i think will fix if we switch to the swap styel UI 
<img width="469" alt="image" src="https://user-images.githubusercontent.com/37959170/211101810-fc647aba-7a3b-4d38-88bd-902bf958ea0a.png">

**Comment by alexwhte** [comment]
@nrsirapop Per convo in discord I didnt mean for us to pull out of backlog yet, but we might as well update in staging since we started. Can you revert and put this in a staging state but make the below updates as well?

1. Balances are is top right above the boxes. Font is slightly brighter for numeric amount
#A5A5A5
#F0F0F0/* 
Balance: 124 ETH */
position: absolute;
left: 72.98%;
right: 0%;
top: 0%;
bottom: 80.23%;

font-family: 'Manrope';
font-style: normal;
font-weight: 600;
font-size: 12px;
line-height: 140%;
/* identical to box height, or 17px */

2. The outline of the 'Receive' box is darker color to signal it is not editable  
Receive
border: 1px solid #292929;
border-radius: 3px;
vs. the Pay with
border: 1px solid #3E3E3E;
border-radius: 3px;

3. Fees are slightly darker follow this formatting ![image.png](https://images.zenhubusercontent.com/626ab10ca26fcfea2fcdf2e1/71a1de5f-7078-4e14-adb9-1c6581e35fe3)

Following this design https://www.figma.com/file/Z3iq2LOM12K1BeSGQc1Dal/Connext-Concept?node-id=190%3A500&t=rCyfDPIVJCGG1sGg-0

**Comment by alexwhte** [comment]
I love it! Lets ship it

**Comment by sanchaymittal** [comment]
Implemented, nice work @nrsirapop. Closing it.
