### ISSUE TITLE
As a [end user], I want a checkbox in order to indicate that a receiving address is an exchange address

### ISSUE THREAD

**Issue by Tommy-R8** [connext/monorepo#2476]
## Problem
If a transaction exceeds slippage, the user would receive Next assets. If the receiving address is an exchange deposit address, the user is likely to lose their funds because they won't recognize the Next assets.

## Proposed Solution
Ideal solution would be a checkbox that allows for a callback to happen if slippage is too high, and returns the funds to origin. But that involves a lot of dev work.
In the meantime, I suggest having a checkbox that when checked displays a message about the risk that exceeding slippage presents when sending to a CEX deposit address.

## Acceptance Criteria
A simple checkbox that is able to display a message.

**Comment by alexwhte** [comment]
We have two options 
- bump slippage (waiting for eng capacity) https://github.com/connext/nxtp/issues/2094
- receive local nextAsset (debating if we even allow this still because UX is so bad)

Does this hinge on if we allow user to choose to receive local? I think it's a great callout if it's to Coinbase or w/e and they get fucked

I would love to revert to sending wallet as you noted it was too complex

**Comment by alexwhte** [comment]
@Tommy-R8 are you aware of a way to see if a receiving address is an exchange deposit address?

**Comment by Tommy-R8** [comment]
I'm not aware of a way to see this but a disclaimer and a checkbox when the user fills in the receiving address field should suffice

**Comment by sanchaymittal** [comment]
@Tommy-R8 I'm not sure, how can we detect an exchange address?

Also, referring to the issue problem, the user will be able to change the slippage or revert the transfer if required. Both issues are in pipeline. Starting with slippage bump implementation.

closing this issue for now, let's re-open it if required.
