### ISSUE TITLE
Incorrect slow vs fast estimate in Latest Transfers

### ISSUE THREAD

**Issue by alexwhte** [connext/monorepo#2825]
**Describe the bug**
Transaction shows slow path in main Transfer Status but fast path estimate in Latest Transfers 

I think this is SLOW path  but it doesnt say so in the Explorer
https://amarok.connextscan.io/tx/0xe861cde1c1f70be17929d1628b3a4fbac152cbdf9374cbba52bf91fcb5ddd9f3

![image](https://user-images.githubusercontent.com/37959170/209199587-9322c4cf-6af0-4832-8a58-22a34bcc7af2.png)

![image](https://user-images.githubusercontent.com/37959170/209199191-c7b2d43b-5682-4271-bff7-02d0fb858e5b.png)

**Comment by pjenviri** [comment]
This could be because there is no response information indicating which transfer type (fast or slow path) is for this transaction. (https://discord.com/channels/454734546869551114/909827059373723648/1040516953632157776, https://discord.com/channels/454734546869551114/909827059373723648/1040688562166845440)

Please let us know if any data field can be used. Thank you.

**Comment by sanchaymittal** [comment]
seems to be resolved in past week.
