### ISSUE TITLE
Transfers where we wrap asset are logging with incorrect wallet/contract address?

### ISSUE THREAD

**Issue by alexwhte** [connext/monorepo#2905]
**Describe the bug**
I'm not seeing all latest transfers for my wallet 0x6d91e35d502fb6f654992283e6e4f397fc23dc2c
in connectscan  https://amarok.connextscan.io/address/0x6d91e35d502fb6f654992283e6e4f397fc23dc2c

It seems to be splitting out the Optimism source transfers where we need to wrap ETH, because we are logging the 'To:' contract in here as the Caller https://optimistic.etherscan.io/tx/0x27eb3abf96648ef82be55e2b49953f4759971335fb3f69c73af16710505ddef8

My missing transfers are under that contract here: https://amarok.connextscan.io/address/0xb0eef3e1de973d045c3858e072c540299585252d

So is reflecting these Optimism transfers in the Latest Transfers section still
But when you click out to 'See More' it links to my wallet
https://amarok.connextscan.io/address/0xb0eef3e1de973d045c3858e072c540299585252d

![image](https://user-images.githubusercontent.com/37959170/210454882-b06fb961-d422-45a8-bda1-8ff177a664ab.png)

**Comment by alexwhte** [comment]
For Arbitrum seeing similar weirdness 
My wallet is 0x6d91e35d502fb6F654992283e6E4f397fC23DC2c

![image](https://user-images.githubusercontent.com/37959170/210456248-031c08aa-7311-4fbb-a671-4abd1a400b41.png)

The transfer is 
https://amarok.connextscan.io/tx/0xf09ad6a535681c3f44debce58509f976e1e7556e4fbc710344e5db473f3d063e

Caller: 
0x20c2a9430baa7251eb9143cbe80ac3968893d06c

https://arbiscan.io/tx/0xad7242b42965e929acb8d7360432d8f6759136b8a12cec653378d86536821ec4

**Comment by alexwhte** [comment]
not sure if related to #2642

**Comment by just-a-node** [comment]
This one is because it's coming from the Multisend contract. Unfortunately, the "caller" of the xcall in this case will always be the Multisend contract.

If we want, the UI could implement some custom logic to always consider the originating EOA from the bridge UI as the sender and then we can display the right transfers under each EOA.

**Comment by alexwhte** [comment]
IF i understand this would help users see all their transfers together

But I think this has some bigger data cleanliness/quality implications beyond the UI

In many cases we will want to analyze unique users over time and related data on-chain  (ex/ https://twitter.com/HopProtocol/status/1608960136604962817)

It will likely incorrectly show one of our biggest users as the Multisend contract, unless we always join a weird way? Can we even do that still?

**Comment by just-a-node** [comment]
Each `xcall` transaction still has record of the EOA that originally sent the call so we can use this on UI side to display the "sender" and filter all of an EOA's transfers correctly. If our tracking system uses the "from" address in the same way, we can get to unique addresses.

**Comment by jakekidd** [comment]
The "tracking system" above could be carto... I'm not sure what other resources we'd have available as a team for this kind of thing. We'd have to use some database for recording this, otherwise the user will be consuming a provider to check tx by tx (since presumably, it's easy enough to get all xcall tx hashes) who the EOA caller was, which would be massively inefficient.

**Comment by pjenviri** [comment]
The UI displays the data getting from `getTransfersByUser`.

**Comment by rhlsthrm** [comment]
Oops I submitted a dup #2931 , fixed there also.
