### ISSUE TITLE
Binance pool price impact failures 

### ISSUE THREAD

**Issue by alexwhte** [connext/monorepo#3080]
When im in binance pool https://amarok.bridge.connext.network/pool/USDC-on-binance

When I add 199 it shows -99% price impact which doesn't make sense 
![image](https://user-images.githubusercontent.com/37959170/212789278-5e2e8d32-40e0-44e7-8f1c-04dd25e5c3f0.png)

When my wallet is not yet connected and I enter 1 in the USDC side it throws an error

> calculateAddLiquidityPriceImpact error] {domainId: '6450786', contract_address: '0x8AC76a51cc950d9822D68b83fE1Ad97B32Cd580d', amountX: '1000000000000000000', amountY: '0', error: Error: call revert exception; VM Exception while processing transaction: reverted with reason strin…}

![image](https://user-images.githubusercontent.com/37959170/212777037-9d3c27f8-5f44-4fb0-bb22-ebccc4cacb40.png)

**Comment by alexwhte** [comment]
low pri unless this points to a bigger issue

**Comment by alexwhte** [comment]
bumping user found it https://discord.com/channels/454734546869551114/1063086012282196098

**Comment by alexwhte** [comment]
also this fails in many cases 
![image](https://user-images.githubusercontent.com/37959170/212789587-a7e17402-6dfe-4cff-81b0-de5ae0bcd913.png)

**Comment by just-a-node** [comment]
@pjenviri See the call to `addLiquidityPriceImpact` below - the input amount has the wrong decimals. It should be called with the token's native decimal precision because the sdk method does the conversion automatically.

![image.png](https://images.zenhubusercontent.com/63331d421176573c6a908c0e/54cc3eb7-a6a3-4e37-ab43-67f967fdaa14)
