### ISSUE TITLE
Price impact behavior is opposite on all pools

### ISSUE THREAD

**Issue by alexwhte** [connext/monorepo#3146]
**Describe the bug**
When providing the underweighted asset in any pool, I'm seeing the opposite of expected behavior. Im seeing
1. positive price impact
2. An error to provide the underweighted asset (which i already am) 

**To Reproduce**
1. Go to any USDC pool, for example
 https://amarok.bridge.connext.network/pool/USDC-on-arbitrum
3. Enter nextUSDC amount
4. See behavior

**Additional context**
<img width="1352" alt="image" src="https://user-images.githubusercontent.com/37959170/213614786-1d40a9a3-acaf-4ef8-ab6e-accd1e036ef2.png">

<img width="1362" alt="image" src="https://user-images.githubusercontent.com/37959170/213614860-924f0b88-9892-42f9-a211-3745b70282ba.png">

**Comment by alexwhte** [comment]
Critical as this impacts LP campaign and associated tutorials/content

**Comment by pjenviri** [comment]
The current UI checks whether the sum of the filled amount and the current amount in the pool is overweight or not. To fix this, we will make some changes to check whether the user enters more amount on the asset that needs to be added more. If yes, then the UI will not show the warning message.

**Comment by alexwhte** [comment]
@pjenviri I think the issue is actually a bit different.
The price impact should not be positive, it should be negative. I'm providing the underweighted asset so I should be paying a discount for LP tokens 
![image](https://user-images.githubusercontent.com/37959170/213746434-e9b65c2a-cd66-4a05-9a1f-b48df561b975.png)

**Comment by alexwhte** [comment]
Please move to our ToDo column if this needs SDK investigation?

**Comment by just-a-node** [comment]
The reason they're flipped is because the pool token indices aren't always [local, adopted]. @pjenviri The UI should reference the pool object from `getPool` to see what index each token is in, for example for Optimism USDC:

```
{
  "domainId": "1869640809",
  "name": "nextUSDC-Pool",
  "symbol": "nextUSDC-nextUSDC",
  "local": {
    "address": "0x67E51f46e8e14D4E4cab9dF48c59ad8F512486DD",
    "name": "nextUSDC",
    "symbol": "nextUSDC",
    "decimals": 6,
    "index": 0,
    "balance": {
      "type": "BigNumber",
      "hex": "0x0bbf590821"
    }
  },
  "adopted": {
    "address": "0x7F5c764cBc14f9669B88837ca1490cCa17c31607",
    "name": "USD Coin",
    "symbol": "USDC",
    "decimals": 6,
    "index": 1,
    "balance": {
      "type": "BigNumber",
      "hex": "0x10b3f9db24"
    }
  },
  "lpTokenAddress": "0xB12A1Be740B99D845Af98098965af761be6BD7fE",
  "canonicalHash": "0x6d9af4a33ed4034765652ab0f44205952bc6d92198d3ef78fe3fb2b078d0941c"
}
```
Local is index 0 and adopted is index 1 but the UI assumes right now that [adopted is always index 0 and local is always 1](https://github.com/CoinHippo-Labs/connext-bridge/blob/9ba80d77e506d27b41240f187d0df749d39aabb2/components/pool/liquidity.js#L532).

**Comment by pjenviri** [comment]
@just-a-node , we have already checked the token indices. As per @alexwhte 's input, the calculated price impact is; `amountX` = `local` and `amountY` = `adopted`.

When the price impact was positive but no warning messaging showed up, that was because the user tended to add the underweight amount. Otherwise, the message will show up. ![Screenshot_2566-01-22_at_01.17.28.png](https://images.zenhubusercontent.com/621e3b767b1b68643061275d/7a19a7f8-326a-4aaa-b7d4-cd4a984c8422)


Similar to the Optimism case below.![Screenshot_2566-01-22_at_01.22.10.png](https://images.zenhubusercontent.com/621e3b767b1b68643061275d/f140cf4c-1caa-424e-8e4f-9ff80bececd9)

Please let me know if I misunderstand something. Thanks! cc. @nrsirapop

**Comment by just-a-node** [comment]
@pjenviri sorry for the confusion - you are doing this correctly with the indices.

The price impact is actually positive when the user will be provided *bonus* LP tokens and vice versa. So we need to switch the logic for the pop-up.

Basically, the pop-up should show only when the price impact is negative AND the user is trying to supply the adopted asset.
