### ISSUE TITLE
Non-disappearing InsufficientRelayerFee warning 

### ISSUE THREAD

**Issue by oswy-cpu** [connext/monorepo#3173]
**Describe the bug**
After paying for an additional relayerFee, the warning does not disappear in the connextscan UI, the transaction is finalized.

**To Reproduce**
2. 
3. 

**Additional context**
<details>
  <summary>Screenshot and tx link</summary>

<img width="1432" alt="image" src="https://user-images.githubusercontent.com/74738120/213859241-b41b228d-f80c-46af-909b-d64590e13785.png">

https://amarok.connextscan.io/tx/0x40f8516720a86ab6146a78156dcab9f18f8d36c99f54db30f73cacde3bb4ed66?_gl=1*1b63fwj*_ga*MTEwODg5NTQxNy4xNjc0MTA4MTg3*_ga_MPYZEDRVQ0*MTY3NDI4ODgyOS40LjEuMTY3NDI4OTg3MS4wLjAuMA

</details>

**Comment by oswy-cpu** [comment]
In addition to the fact that users continue to see a "InsufficientRelayerFee" warning, bump does not help to complete the transaction.
<details>

<img width="1372" alt="image" src="https://user-images.githubusercontent.com/74738120/213909436-21fcc99a-d6c1-4c11-afe1-3143122fd996.png">
https://amarok.connextscan.io/tx/0x17da3987fe3a5d36c4a190e2ba7bdbe628ffe562e6643e87513650d90fd5e92c?_gl=1*1gxnf87*_ga*MTIzNzQxODEyNi4xNjcyNDc4NzA4*_ga_MPYZEDRVQ0*MTY3NDMzODMyOC4zLjEuMTY3NDMzODM1MC4wLjAuMA

</details>

**Comment by doxe1** [comment]
Yes, I agree. The problem is still ongoing, so here is another example, he tried several times, but alas without results.
![Connext-1](https://user-images.githubusercontent.com/84589100/213935702-130a42fe-3887-4c46-9102-56a632029e36.png)
![Connext-2](https://user-images.githubusercontent.com/84589100/213935704-a596c2ec-696e-4351-bde2-684dc1bb2f7f.png)

Link on Optimism scan - https://optimistic.etherscan.io/tx/0xdee427851be2f0eb726c4f11188dc16e5f84bd0b46c484e5d83c6091aec20302.

**Comment by alexwhte** [comment]
Leaving this open as the issue is `estimateRelayerFee` is apparently too low and not clearing

For better UX when they are cleared, please track https://github.com/connext/monorepo/issues/3011#issuecomment-1398642970

**Comment by alexwhte** [comment]
@oncall please merge with https://github.com/connext/monorepo/issues/3175 if it makes sense

**Comment by sanchaymittal** [comment]
resolved the above bugs
