### ISSUE TITLE
Sequencer retries acting buggy

### ISSUE THREAD

**Issue by rhlsthrm** [connext/monorepo#3182]
**Describe the bug**
Title

**To Reproduce**
Start transfer on mainnet, check DataDog logs for that transferId

**Additional context**
It seems like some combination of router retries plus sequencer not properly checking for destination transfer in the right place is causing this.

https://app.datadoghq.com/logs?query=%40requestContext.transferId%3A0xc354b4d5921b11b8c25dbac938de0e2e877b50ed1b5c37c837fbd3d39f29fc8f&cols=service&index=mainnet-production&messageDisplay=inline&stream_sort=time%2Cdesc&viz=stream&from_ts=1674477430027&to_ts=1674481030027&live=true

<img width="1190" alt="Screenshot 2023-01-23 at 17 55 28" src="https://user-images.githubusercontent.com/11512787/214057253-676d676f-4937-47d3-8b4a-3cf845a707cf.png">

**Comment by preethamr** [comment]
This is new behavior because of router retries on incomplete xcalls.

This transfer was executed in fast path, in ~40 seconds.

https://app.datadoghq.com/logs?query=%40requestContext.transferId%3A0xc354b4d5921b11b8c25dbac938de0e2e877b50ed1b5c37c837fbd3d39f29fc8f&agg_q=status%2Cservice&cols=service&context_event=AYXe27c2AAD9KASHXcPkDAAA&event=&index=mainnet-production&messageDisplay=inline&sort_m=%2C&sort_t=%2C&stream_sort=time%2Casc&top_n=10%2C10&top_o=top%2Ctop&viz=&x_missing=true%2Ctrue&from_ts=1674480919382&to_ts=1674481279382&live=false

But the subgraphs take some time to update status, and the routers to stop retrying, and the pending messages from previous router bids to be removed from the message queues.

This can be reduced by adding a exponential back off for routers while retrying, and to change how sequencer handles repeat/retry bids. Sequencer should handle bids differently, if a previous bid was successfully submitted to relayer, but successful execution has not been confirmed.

**Comment by rhlsthrm** [comment]
> Sequencer should handle bids differently, if a previous bid was successfully submitted to relayer, but successful execution has not been confirmed.

I think this is the right solution. If the routers send bids as part of their retry mechanism on their 30 second poll interval, it's fine. However, the sequencer is already storing the exec status when it sends to relayer: https://github.com/connext/monorepo/blob/main/packages/agents/sequencer/src/lib/operations/execute/fastpath.ts#L404

The best solution would be this:
- Make sure the Sent status expires after 5 minutes or so, so that retries can be handled appropriately.
- On the sequencer publisher side, check if status = Sent, and if so, drop the message right there. No need to have any subscriber action in this case.
