### ISSUE TITLE
Missing sdk dependancy 

### ISSUE THREAD

**Issue by brozorec** [connext/monorepo#3201]
**Describe the bug**
After upgrading to "@connext/nxtp-sdk": "^0.2.1-rc.16", it doesn't seem to find "@eth-optimism/sdk" module and throws the following error:

```
error - ../../node_modules/@connext/nxtp-contracts/dist/src/utils.js:9:0
Module not found: Can't resolve '@eth-optimism/sdk'

Import trace for requested module:
../../node_modules/@connext/nxtp-contracts/dist/src/index.js
../../node_modules/@connext/nxtp-sdk/dist/sdkShared.js
../../node_modules/@connext/nxtp-sdk/dist/index.js
```

I needed to downgrade the package to "@connext/nxtp-sdk": "0.2.1-rc.13" to make it work.

**To Reproduce**
2. 
3. 

**Additional context**

**Comment by goerris** [comment]
I'm having similar problems but regarding ESM.
We are using Vite and cannot use require().

Could not resolve "@eth-optimism/sdk"

    node_modules/@connext/nxtp-contracts/dist/src/utils.js:9:22:
      9 │ const sdk_1 = require("@eth-optimism/sdk");
        ╵                       ~~~~~~~~~~~~~~~~~~~                                                                                                                           

  You can mark the path "@eth-optimism/sdk" as external to exclude it from the bundle, which will
  remove this error. You can also surround this "require" call with a try/catch block to handle this
  failure at run-time instead of bundle-time.

Error [ERR_REQUIRE_ESM]: require() of ES Module /..../ node_modules/@connext/nxtp-contracts/dist/src/domain.js not supported.
Instead change the require of index.js in /..../node_modules/@connext/nxtp-contracts/dist/src/domain.js to a dynamic import() which is available in all CommonJS modules.

Any way to solve this? 
Want to use the estimateRelayerFee function.
