### ISSUE TITLE
Galxe Campaign Subgraph cred deployment 

### ISSUE THREAD

**Issue by A-Keyboard** [connext/monorepo#3273]
In order to track the users depositing LP on multiple chains, we need to deploy a Subgraph credential, and pull addresses that provided liquidity.

Doc: https://docs.galxe.com/developer/guide/subgraph-cred/

**Comment by rhlsthrm** [comment]
We figured out this is not going to be possible to do with the subgraph. Instead we will use the API method: https://docs.galxe.com/developer/guide/api-cred-items-update/

This requires:
- Calculate in the stableswap poller the top 30% of LPs.
- Send addresses to Galaxe API.

**Comment by rhlsthrm** [comment]
Since this is snapshot based, there's an easier solution. We can simply take snapshots manually and upload CSVs here: https://galxe.com/dashboard/credential?space=307&type=evm_address&source=CSV

No point in automating this since it's a one-time thing. @liu-zhipeng 's linked PR provides the DB views we need to gather this info.

**Comment by rhlsthrm** [comment]
We will do this with a script at the time of distributing the NFTs. Closing this out.
