### ISSUE TITLE
Ability to withdraw custom amounts from pools

### ISSUE THREAD

**Issue by alexwhte** [connext/monorepo#3369]
## Problem 
User requested this 
It makes sense if you cant use nextUSDC after removing, you need to swap anyways and may have slippage. If you provide USDC you want to get back USDC. 

![image](https://user-images.githubusercontent.com/37959170/216488827-2ede9d11-0f23-4674-868f-248aa6217275.png)

## Solution
Contracts support this 
We can consider a slider for the user to decide the amount or % of each

**Comment by Tommy-R8** [comment]
https://discord.com/channels/454734546869551114/1053026258021257316/1071084455239888966

**Comment by alexwhte** [comment]
show 3 radio button options with a slider underneath that is disabled except for option 3
option 1: One asset
Radio buttons for either: 
Adopted 
Local

Option 2: Balanced amounts
Preview amount user will receive

Option 3: Custom amounts 
Show a slider underneath 

ideas here are from Curve https://curve.fi/#/ethereum/pools/3pool/withdraw

https://docs.connext.network/developers/reference/SDK/sdk-pool#removeliquidity

**Comment by pjenviri** [comment]
@just-a-node, please attend the URL with `?mode=test`.

**Comment by pjenviri** [comment]
@just-a-node, please attend the URL with `?mode=test`.

**Comment by just-a-node** [comment]
To clarify what withdrawing in "balanced amounts" is - receive amounts of asset X and asset Y in the same distribution of the pool's current asset weights. 
- For example, if there are 45 asset X and 55 asset Y in the pool, withdrawing 10 LP tokens will return 4.5 asset X and 5.5 asset Y

Some suggestions to confirm with @alexwhte:

1) Should be more clear to the user that the percentages here refer to the % of their total LP token balance to withdraw (this will automatically return the "balanced amounts" of each token)

![Image](https://user-images.githubusercontent.com/16638982/223325717-7249fdb3-07e6-4871-b16e-6f03443a5108.png)

2) "Balance" option is not needed then, here:

![Image](https://user-images.githubusercontent.com/16638982/223326434-8f1cd6cd-18c0-4a00-9b63-add07f1c0fd3.png)

3) Should show price impact for custom amount withdrawals because users may not understand that withdrawing in non-balanced amounts is detrimental to their price impact.  Can still use `calculateRemoveLiquidityPriceImpact` with the specified amount of each asset.

4) The slider is way too granular (at 0.01% precision right now). Probably better to use notches to slide +/- 5% or 10% at a time. This also affects performance, every change in the slider right now is calling `removeLiquidityPriceImpact`.

5) The slider direction is a bit unintuitive. Sliding to the right feels like "I want more rightAsset" but in this case it actually increases the amount of leftAsset. When you click the the "Only (rightAsset)" button, the slider moves all the to the left. 

![Image](https://user-images.githubusercontent.com/16638982/223328297-2b6090d8-90c6-4ca5-8191-f6b5cc94ff82.png)

If we want to keep this direction, it would be more clear if we showed a bar thing like this:

![Image](https://user-images.githubusercontent.com/16638982/223328967-c7aeee11-7fe1-4b35-af11-6cdbdebacb5c.png)

**Comment by alexwhte** [comment]
Sorry for delay on this, please try this design instead

**User selected percentage to withdraw**
Show them the balance of tokens they have

**User selects distribution**
- balanced amounts
- single asset only
- Custom amounts

IF balanced amounts OR a single asset is selected THEN the 'You receive' amounts are locked/grey
IF custom amounts is selected THEN the 'You receive' amounts are typeable.

IF a single asset or custom amounts are selected, then slippage impact is calculated and displayed

<img width="835" alt="image" src="https://user-images.githubusercontent.com/37959170/223338835-2ca7b08a-19e5-4a55-8e7a-0d46549f5737.png">

**Comment by just-a-node** [comment]
LGTM, few suggestions for Coinhippo when implementing:

- Use "LP Token Balance" for "LP Tokens" and make sure the text for "LP Token Balance" and "Balances" are smaller/slightly greyed out compared to the "Withdraw percentage" and "You receive".

- For the radio button selection, black = selected? Deferring to Coinhippo on what to use but something more clear would be nice like this:

![image](https://user-images.githubusercontent.com/16638982/223726649-b95ab091-d50b-49c9-bf0e-99900d05fe34.png)

**Comment by alexwhte** [comment]
this works!

**Comment by pjenviri** [comment]
you can test it by appending `?mode=test` as usual. However, it will revert.

**Comment by alexwhte** [comment]
Confirmed im seeing an error reverted.. passing to eng

**Comment by liu-zhipeng** [comment]
https://github.com/connext/monorepo/pull/3810/

@just-a-node  I added corresponding functions for `removeLiquidityOneToken`, `removeLiquidityImbalance`.  Please let me know if you have any other requirements or help.

**Comment by just-a-node** [comment]
Next steps:
- SDK release `1.2.0-alpha.1`
- UI changes to use new methods (`calculateRemoveSwapLiquidityOneToken`, `removeLiquidityOneToken`) when user wants to withdraw amounts in only 1 token

**Comment by just-a-node** [comment]
QA'd "withdraw balanced" and "one token" for both tokens. But the "withdraw custom" call is reverting:
![image.png](https://images.zenhubusercontent.com/63331d421176573c6a908c0e/2faaeea0-a917-4f43-b9ef-5f7f35861cc2)

@pjenviri I missed a step above for UI change: "withdraw custom" needs to call `removeLiquidityImbalance` with different params (https://docs.connext.network/developers/reference/SDK/sdk-pool#removeliquidityimbalance).

**Comment by pjenviri** [comment]
updated. Please it at https://connext-bridge-mainnet-git-feat-update-pool-ui-coinhippo.vercel.app.
