### ISSUE TITLE
sequencer has bad data for transfer either it isn't updated or some other issue

### ISSUE THREAD

**Issue by sanchaymittal** [connext/monorepo#3571]
**Describe the bug**

The sequencer has bad data for transfer either it isn't updated or some other issue
Solution:
--- temp fix: wiping the cache for transferId
--- permanent fix: Pull the data of a transfer from subgraph instead of cache.

**To Reproduce**
2. 
3. 

**Additional context**

**Comment by preethamr** [comment]
Transfer:
https://connextscan.io/tx/0x10b611db8bc036318396877d93f756c474abfe974f735ed2f42bc917cc3e0daa

**Comment by preethamr** [comment]
Investigated this, findings:

Sequencer already pulls the latest transfer info from subgraph, every time a fast or slow path request is received, and cache is updated (upserted) with the new data, if any transfer info changed.
For fastpath:
https://github.com/connext/monorepo/blob/eddd80448e6457d8d8ce5f097797dc79af81a1f0/packages/agents/sequencer/src/lib/operations/execute/fastpath.ts#L55

For slowpath:
https://github.com/connext/monorepo/blob/eddd80448e6457d8d8ce5f097797dc79af81a1f0/packages/agents/sequencer/src/lib/operations/execute/slowpath.ts#L51

Further I simulated a these scenarios in prod testnet:
1. zero relayer fee transfers, with user CTA, and user bumps fee, and sequencer executes this in fastpath
2. zero relayer fee transfers, with user CTA, and user bumps fee, and sequencer executes this in slowpath
3. Non-zero, but low, relayer fee transfers, with user CTA, and user bumps fee, and sequencer executes this in fastpath
4. zero relayer, but low,  fee transfers, with user CTA, and user bumps fee, and sequencer executes this in slowpath

Conclusion:
This is v likely not sequencer data issue.
Instead, this was caused by subgraph data for the transfer not reflecting the fee bump, reason for which is unknown.

**Comment by sanchaymittal** [comment]
we are still running into issues where the sequencer doesn't have the updated transfer data after bumping on relayerFee.

some transfers to debug logs:
- 0x3d722c2d99cf21861c7f2d10dbabd84c76200fc6075190e2093f7023bed2a536
- 0x9108303120c4fb07927ba8b1a334a5839200f41433a4c77ffd22caab26c39f11
- 0x2ee100186dbd12670ab7fda0cd0f3071508c67d9a42bda2f5d694f963ed87ebe


TempSolution: Cleaning up cache

Solution needed:
- read the data from subgraph for transferId for each iteration.
- At carto, we will need to reset backoff if we bump relayerFee and slippage(probably already in code, just need to confirm)

**Comment by preethamr** [comment]
The root cause for this behavior is this issue:
https://github.com/connext/monorepo/issues/3644

Will move this to QA, as sequencer cache upsert on fee change does not seem to be the issue.

**Comment by preethamr** [comment]
AFAIK this is not observed anymore.
