### ISSUE TITLE
SDK with React [Fjord]

### ISSUE THREAD

**Issue by just-a-node** [connext/monorepo#3749]
## Background

SDK should work out of the box for React integrations. 

Context from Fjord:
```
when installing the SDK in a fresh React app you get a few errors that require webpack configuration/polyfill
```

### Linked Issues & Documentation

- List of linked issues, external links, etc

## Definition Of Done

Describes in 1-2 sentences what the output of the Task is, so that it can be verified by another team member easily. “Feature X is implemented as described and can be verified by using it”

## Tasks

- [ ] Task 1
- [ ] Task 2
- [ ] Task 3

**Comment by ArjunBhuptani** [comment]
More info:

1. Here's the error. They created a sample repo to repro here:  https://github.com/kryptachio/connext-test/commits/main
![image](https://user-images.githubusercontent.com/22877754/224335741-e200c246-9d8c-464e-a7e6-fb723a6b1590.png)

2. They said they solved the above issue, but then ran into issues with Axios because they are using v0.21.4 in their app whereas we use v1.3.3. They tried upgrading but weren't able to on their end.
![image](https://user-images.githubusercontent.com/22877754/224335876-4349892e-40ff-4f87-974a-004ee8a60d5a.png)

**Comment by rhlsthrm** [comment]
This is a known issue with polyfilling create-react-app. There are easier ways to integrate Connext SDK. Documented here: https://docs.connext.network/developers/guides/sdk-frontend-integration

Will revist a larger SDK refactor to reduce the deps to really only the necessary ones.
