### ISSUE TITLE
Off-Chain spec for Optimistic Roots

### ISSUE THREAD

**Issue by preethamr** [connext/monorepo#3819]
Complete the specification for off-chain changes.

Details needed:
- [x] Switching mechanism
- [x] Design of new LH agents
- [x] Modifications needed for existing LH agents
- [x] DB changes
- [x] Testing approach

**Comment by alexwhte** [comment]
Standup: Spec should be done today, will task out execution, and work on time estimation 

AI: Set up a test environment for both teams to collaborate and use 
We have upgrades to contract + offchain and need to test it all in an environment 
- Doesnt touch anything else 
- Both Wonderland and Connext can build 

Can we use Harbor? Main blocker is getting deploy script and AMBs set up. Ask Harbor if they have a solution for AMBs. Otherwise we can't use this without significant more eng work

Alternative: Pull out changes from local xDeposit hackathon to deploy subgraph and env to local testing 

Wait until this is ready to test, if staging is not used then use staging. Otherwise spin up a new environment
Change CI flow so testnet-prod and mainnet-prod are triggered off different branches 

We need to figure out and scope exactly what integrators need

**Comment by alexwhte** [comment]
No blockers, fleshed out almost all details of offchain agents
Now it is minimal things left
Prototype today/tomorrow
