### ISSUE TITLE
Reconciliation failures 

### ISSUE THREAD

**Issue by alexwhte** [connext/monorepo#4156]
https://discord.com/channels/992549151134982234/1105163410615828480/1105207513420402959

**Comment by LayneHaber** [comment]
Update:

- Roots are being dispatched from BNB, but aren't landing on the `RootManager`, with the latest `RootReceived` event being from [this transaction](https://etherscan.io/tx/0x983bf00c1c85eefe7175e3b85564e4652888db6f50bb5b3e8d336511e406e93e) roughly 1 day ago, found via contract events.
- BNB is receiving aggregate roots, but cannot include its spoke root in these values
- Since multichain is having problems in one direction only, I wonder if it is a fee issue. However, we have not been able to find the transaction in the explorers
- I opened a ticket with their support team, but haven't heard back

Some sample transactions showing roots being dispatched but not yet received:

```
0x22f12645f3526330b68fefbe5c99a9c17fe6016db5d50752c1207b1ba5c278bd
0xd88a794e583e9cd0871f542e53175664359230ced78d214ddb0b57f38c3c8538
0x7fb39a782d3fef363a3826af3e78f1ea2dfc701793dd6bc7a2641f5ddb6fb0e0
0xef3dc8cc7a456692ec521baec596106ea098f699adb37a6f3c8acaaa1a6934c9
0xcdb29808e78c27c2c3d8f84b81da0232504e7863c88a664eb8f23d185a0bf1fc
0x13067210a84909aa722ca87b42918b30c80819a025d3a017c8c3e5d3deceb980
```

**Comment by LayneHaber** [comment]
update: reached out to multichain support, and they were able to clear these transactions. issue is likely still ongoing as there are now new transactions in the same condition:

```
0xcdb29808e78c27c2c3d8f84b81da0232504e7863c88a664eb8f23d185a0bf1fc
0x13067210a84909aa722ca87b42918b30c80819a025d3a017c8c3e5d3deceb980
0xd5616d2434ac78596e29a97d05fbf5e0d2c729a6f6c65fc5351aa6e4b380cc5d
0x08368b487160913541543a00ca86e7942b702f9cf9b52bfb684da859f04758ca
0x719bd0f814b693c3f8994ffb9d3351a6f63fcd2c089b33ecc5e20ed66937ef07
0x79b4d72a42a0bd210faae6b4f36e06c1477fa042c429f5c78379ae1590aee366
0xd84a0402b8040ba8f73bd95205e78c6ca63d404de5cce2afb230cd65b94c33a7
0xc2889d730e4464e7254049582577db65c0bf6882a8ca5995d5927ef8cbe7f4ca
0xd6de37b859853fe5ef10cf8247e91de7dd242c7ba6c2a1556d9fa9f0cd674815
0xc684d784ad8a48dee8c82e32207b54b1c4aec5aee6e8b58c6767a18cf8364ab7
```

**Comment by alexwhte** [comment]
multichain closed our ticket /sad
filing new one

**Comment by alexwhte** [comment]
fixed
