### ISSUE TITLE
Pending Boost on USDT Polygon to Gnosis

### ISSUE THREAD

**Issue by Tommy-R8** [connext/monorepo#4176]
**Describe the bug**
A transaction has been going on for 1hr+ because it wasn't boosted by a router. There should be a ton of nextUSDT router liquidity available and the pools are also very liquid. https://connextscan.io/tx/0x5b3599de4579115715bbd61b197db0e912a0955d06472597c637323f2c622fb9?src=search

**Additional context**
https://discord.com/channels/454734546869551114/1105561297141125170/1105562143274848307

**Comment by Tommy-R8** [comment]
Another one. The one posted at the top completed (looks like through the slow path)
https://connextscan.io/tx/0x68e34ac500758dacc5b7841452cfa24b2728ed5dfa44c83d6ea802039ad7b12f
https://discord.com/channels/454734546869551114/1105596600966975689/1105596690259521646

**Comment by Tommy-R8** [comment]
Another one. Going on for 2h.
https://connextscan.io/tx/0x2124469c3adebf01d4d345d7c155e2e5f6a2879b3d09a74133fd158698e4f02a?src=search
https://discord.com/channels/454734546869551114/1105655746928070686/1105655886426419210

**Comment by alexwhte** [comment]
these are settling slow path , so lower reliative priority

**Comment by rhlsthrm** [comment]
Need some better logging. This is concerning because I do see that some router bids came in, but I don't see it executing OR erroring:

https://app.datadoghq.com/logs?query=service:sequencer%20@requestContext.transferId:0x72a70bba8ab2596f66de00d1b6671a1f13396135e3092fe1c955fe9cd2c0b111&cols=service&index=mainnet-production&messageDisplay=inline&saved-view-id=1285114&stream_sort=time,asc&viz=stream&from_ts=1683634053755&to_ts=1683806853755&live=true

**Comment by LayneHaber** [comment]
looked a little closer, not sure if that's the case. for some of these it seems there were bids, but not enough liquidity. will investigate one-by-one

**Comment by rhlsthrm** [comment]
Probably due to the gnosis router outage.
