### ISSUE TITLE
TestAsset has been setup incorrectly on linea

### ISSUE THREAD

**Issue by wanglonghong** [connext/monorepo#4381]
**Describe the bug**
The canonical id of `TestERC20` should be `0x0000000000000000000000007ea6ea49b0b0ae9c5db7907d139d9cd3439862a1`. but on linea it is `0x000000000000000000000000b4fbf271143f4fbf7b91a5ded31805e42b2208d6`

The`TestERC20` token transfers to linea are getting stuck forever due to the incorrect asset setup

**Comment by LayneHaber** [comment]
Update:

- Both canonical ids registered onchain with the same TEST asset
- The subgraph was storing the `Asset` entity under the `local` address emitted in the event
- When the asset with id `0x000000000000000000000000b4fbf271143f4fbf7b91a5ded31805e42b2208d6` was registered after `0x0000000000000000000000007ea6ea49b0b0ae9c5db7907d139d9cd3439862a1`, because they both shared the same `local` asset, the canonical id was overwritten

Solution:
- Refactor subgraph to store `Asset` entity with `hash(canonicalId, canonicalDomain)`
- Remove the `AssetStatus` entity, and instead add it to the corresponding `Asset` entity
