### ISSUE TITLE
Fjord crosschain deposit wrong destination

### ISSUE THREAD

**Issue by Tommy-R8** [connext/monorepo#5124]
**Describe the bug**
A user tried to make a crosschain deposit into a Fjord bootstrapping pool. It seems that the transaction on destination only partially executed and the funds ended up in a swap target contract instead of the user's address. https://connextscan.io/tx/0xe6c3e7aeaabd49d1678100b1550ecf113f4725fb8488b5a5363f4a5f226f432d

**Additional context**
I contacted the Fjord team and they are aware of the issue. Please continue the conversation with them on the shared group chat.
https://discord.com/channels/454734546869551114/1169792491730522122/1170032778746798261

**Comment by liu-zhipeng** [comment]
https://etherscan.io/tx/0x51e90cf003156d171a770b5a96c3e8f37158fac483e8e18b59ad25d86470c82e

![image](https://github.com/connext/monorepo/assets/57480598/d144e711-907b-4ffc-ab22-354e7b1e0da2)

Amount is `0.155318592558696533 WETH`!

![image](https://github.com/connext/monorepo/assets/57480598/4dd9b9ac-46c5-4c57-bfb0-eafe05f16608)

But the amount which is decoded from `calldata` of `xReceive` function is `0.155535472480465069 WETH`.
So it was reverted while swapping on Balancer because amountIn is greater than balance.
