### ISSUE TITLE
Router unable to withdraw funds

### ISSUE THREAD

**Issue by alexwhte** [connext/monorepo#5162]
**Describe the bug**
This router he cant withdraw with metamask
https://connextscan.io/router/0x49a9e7ec76bc8fdf658d09557305170d9f01d2fa

Said that in his other router this happened but it was fixed 

I can connect you if it helps 

**To Reproduce**
2. 
3. 

**Additional context**

**Comment by LayneHaber** [comment]
need to know the chain they're trying to withdraw from, and ideally the asset as well (though that is less important)

**Comment by LayneHaber** [comment]
trying to withdraw from optimism.

looking at the onchain config, I see this:

```
config for: 0x49a9e7ec76bc8fdf658d09557305170d9f01d2fa
- owner    : 0x52a568eaACD288A984bbaE0c421099626A6e7735
- recipient: 0x8c3a8f18870E618562d359f25F6A2B9FD9AfFC86
```

I set up a router on testnet with some liquidity and the following config:
```
config for: 0xF39085c993fc37C16e07Cee0375Fb3eEA43D3A55
- owner    : 0xa2Ee8DCd2A8A3A54Cf37F6590E5108BbE502B006
- recipient: 0xF39085c993fc37C16e07Cee0375Fb3eEA43D3A55
```

Then tried to withdraw a portion of the liquidity on the connextscan UI while being connected with the `owner` in the config. This transaction succeeded: https://goerli.etherscan.io/tx/0x53806db0b501fcde5fed7f548b530774eb00742a8f10dfdc7a68edf04c97c651

Trying the `max` button also [worked](https://goerli.etherscan.io/tx/0x2d9f4acac203149cbdca386fd387e1238d993711c1427456a19ffc4fd29a4d0a), but could be because I have artificially round numbers

**Comment by LayneHaber** [comment]
worked for router without changes, could be metamask connection issue.
