### ISSUE TITLE
[ST] Incorred USD volume values in looker DB

### ISSUE THREAD

**Issue by alexwhte** [connext/monorepo#5197]
**Describe the bug**
Jay our contributor is working on pipelines from Cartographer into BigQuery db but the data is still incorrect

Please help answer his questions below? I can loop you in to help in tg

> Q1. How to link asset table to transfer table for decimals? -> currently doing this on canonical_id
> A: after doing some deep dive, It look like there is a logic around origin_domain that dictates decimals
> 
> use this as ref: 0xd3b48a423a57829f3970b76c4546c9ac67eaa46589f0048eee9e6bf45adab806
> 
> The issue in raw data:
> {
>   "transfer_id": "0xd3b48a423a57829f3970b76c4546c9ac67eaa46589f0048eee9e6bf45adab806",
>   "canonical_id": "0x000000000000000000000000a0b86991c6218b36c1d19d4a2e9eb0ce3606eb48",
>   "origin_transacting_asset": "0x8ac76a51cc950d9822d68b83fe1ad97b32cd580d",
>   "origin_transacting_amount": "221159783502651317642",
>   "origin_bridged_asset": "0x5e7d83da751f4c9694b13af351b30ac108f32c38",
>   "destination_transacting_asset": "220919091",
>   "destination_transacting_amount": "220867466",
>   "destination_local_asset": "0xf96c6d2537e1af1a9503852eb2a4af264272a5b6",
>   "destination_local_amount": "220919091",
>   "bridged_amt": "220919091",
>   "normalized_in": "221159783502651317642"
> }
> 
> for eg: decimals on domain 6450786 which is BNB chain are off by 12 for USDC
> 
> 
> Q2.  What is the difference between X_transacting_amount <> X_local_amount, Which one to use? Here X: origin/dest
>

**Comment by liu-zhipeng** [comment]
1. Q1. How to link asset table to transfer table for decimals? -> currently doing this on canonical_id
You need to use both canonical id and domain. 
- For Origin Asset decimal: Asset table [`canonical_id`, `domain`] -> Transfers [`canonical_id`, `origin_domain`]
- For Destination Asset decimal : Asset table [`canonical_id`, `domain`] -> Transfers [`canonical_id`, `destination_domain`]

[canonical_id, canonical_domain] is the unique key for an asset like (USDC, USDT, WETH) on all chains.

2. Q2. What is the difference between X_transacting_amount <> X_local_amount, Which one to use? Here X: origin/dest
You should use x_transacting_amount for both sides.
Because of the bridging flow for a asset: 
   `origin_transacting_amount` -> `origin_bridged_amount` (via stable swap) ==> `destination_local_amount` -> `destination_transacting_amount`
Here `origin_bridged_amount` is same as `destination_local_amount`.  And transacting asset to local asset uses local stable swap.

**Comment by preethamr** [comment]
Closing this issue as it has been answered.
@alexwhte We can reopen this if it is still not fully resolved.
