### ISSUE TITLE
[ST] Execution reverted when bridging alUSD from Arbitrum to Optimism

### ISSUE THREAD

**Issue by Tommy-R8** [connext/monorepo#5513]
**Describe the bug**
The user gets an execution reverted error when trying to bridge more than a certain amount.
![image](https://github.com/connext/monorepo/assets/84744304/2f2f96b5-007e-4651-9999-3c5073e38df3)

**Link to ticket in discord**
https://discord.com/channels/454734546869551114/1194283130442493982/1194312782800232518

**Comment by just-a-node** [comment]
This is due to known liquidity fragmentation in the `alUSD` contract. There needs to be enough `nextAlUSD` locked up in [`alUSD`](https://arbiscan.io/address/0xCB8FA9a76b8e203D8C3797bF438d8FB81Ea3326A) to support a transfer. 

<img width="386" alt="image" src="https://github.com/connext/monorepo/assets/16638982/512cf73e-b1f0-4cf9-a915-2ede436c107d">

We would have to build something custom to the `alUSD`/`alETH` tokens in order to notify users of insufficient liquidity. Not something we have planned yet .
